### ISSUE TITLE
Java Services are broken

### ISSUE THREAD

**Issue by svenkeidel** [monto-editor/services-java#1]
Hi,

I recently tried to use the java services with the eclipse plugin. After a little debugging session, I found out that eclipse received a strange message on the sink socket. The message only contained `javaParser`. This does not conform to any of our message conventions.

@wpmp can you investigate the status of java services? In the meantime I will add a schema check inside the broker that optionally can be turned on to test services.

Best,
Sven

**Comment by wpmp** [comment]
Hi,

actually this is not a bug.
I modified the broker to publish Product Messages in topics.
The topic is equal to the service id of a service.
This enables Sinks to subscribe only to specific services if required.
Hence, you always receive two messages, at first the topic (service id) and second the Product Message itself.
This behavior is also used for Discovery.

Best regards

Wulf

**Comment by svenkeidel** [comment]
It's not a bug, it's a feature ^^
